[package]
name = "flatmap"
version = "0.1.0"
authors = ["Roman Shishkin <spark@uwtech.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
log = "0.4.14"
simplelog = "0.9.0"
